server:
  port: 8765

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes: #Dang ky dateway cho currency calculation service . property uri su dung lb:// <ten mudule> dc dky tai eureka
        - id: calculation-service
          uri: lb://CURRENCY-CALCULATION-SERVICE/
          predicates:
            - Path=/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
